api_platform:

  title: 'Part-DB API'
  description: 'API of Part-DB'

  version: '0.1.0'

  swagger:
    api_keys:
      # overridden in OpenApiFactoryDecorator
      access_token:
        name: Authorization
        type: header