# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:

    language_from_cdn: false

    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 50
        #dom: "<'row' <'col-sm-12' tr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pif>>"
        dom: "  <'row'<'col mb-2 input-group' B l> <'col mb-2' <'pull-right' p>>>
                        <'card'
                            rt
                            <'card-footer card-footer-table text-muted' i >
                        >
                        <'row'<'col mt-2 input-group' B l> <'col mt-2' <'pull-right' p>>>"
        pagingType: 'simple_numbers'
        searching: true
        stateSave: true


    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-hover table-sm data-table'

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
