# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: complex_config
    configs:
        complex_config:
            extraPlugins: "markdown"
            toolbar: comment_toolbar
        simple_config:
            extraPlugins: "markdown"
            toolbar: basic
        description_config:
            extraPlugins: "markdown"
            height: 60
            toolbar: description_toolbar


    plugins:
        bbcode:
            path:     "ckeditor/plugins/bbcode/" # with trailing slash
            filename: "plugin.js"
        markdown:
            path:      "ckeditor/plugins/markdown/"
            filename: "plugin.js"
        specialchar:
            path:     "ckeditor/plugins/specialchar"
            filename:  "plugin.js"


    toolbars:
        configs:
            description_toolbar:
                - [ 'Bold', 'Italic', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                - ["SpecialChar"]
                - ["Source"]
            comment_toolbar:
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ]
                - [ 'Styles', 'Format']
                - [ 'TextColor']
                - [ 'Maximize', 'ShowBlocks' ]
                - [ 'Source', '-', 'About']
                - '/'
                - [ 'Bold', 'Italic', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                - [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - [ 'Link', 'Unlink' ]
                - [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ]

