# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: complex_config
    configs:
        complex_config:
            extraPlugins: "markdown"
            toolbar: comment_toolbar
        simple_config:
            extraPlugins: "markdown"
            toolbar: basic
        description_config:
            extraPlugins: "markdown"
            height: 60
            toolbar: description_toolbar
        label_config:
            height: 100
            enterMode: 2
            toolbar: label_toolbar
            extraPlugins: ["partdb_label", "showprotected"]
            allowedContent: true
            font_names: >
                DejaVu Sans Mono/DejaVu Sans Mono;
                DejaVu Sans/DejaVu Sans;
                DejaVu Serif/DejaVu Serif;
                Helvetica/Helvetica, Arial, sans-serif;
                Times New Roman/Times New Roman, Times, serif;
                Courier New/Courier New, Courier, monospace;

    plugins:
        bbcode:
            path:     "ckeditor/plugins/bbcode/" # with trailing slash
            filename: "plugin.js"
        markdown:
            path:      "ckeditor/plugins/markdown/"
            filename: "plugin.js"
        specialchar:
            path:     "ckeditor/plugins/specialchar"
            filename:  "plugin.js"
        partdb_label:
            path:      "ckeditor/plugins/partdb_label/"
            filename: "plugin.js"
        showprotected:
            path:      "ckeditor/plugins/showprotected/"
            filename: "plugin.js"


    toolbars:
        configs:
            label_toolbar:
                - [ 'Bold', 'Italic', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                - ['JustifyLeft', 'JustifyCenter', 'JustifyRight']
                - ["SpecialChar"]
                - ["Source"]
                - "/"
                - ['Format', 'FontSize', 'Font']
                - ['Table', 'HorizontalRule']
                - ['Placeholders']
            description_toolbar:
                - [ 'Bold', 'Italic', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                - ["SpecialChar"]
                - ["Source"]
            comment_toolbar:
                - ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
                - [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ]
                - [ 'Styles', 'Format']
                - [ 'TextColor']
                - [ 'Maximize', 'ShowBlocks' ]
                - [ 'Source', '-', 'About']
                - '/'
                - [ 'Bold', 'Italic', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ]
                - [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                - [ 'Link', 'Unlink' ]
                - [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ]

