# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: complex_config
    configs:
        complex_config:
            extraPlugins: ["bbcode"]
            toolbar: standard
            height: 100
        simple_config:
            extraPlugins: "bbcode"
            toolbar: basic
        description_config:
            extraPlugins: "bbcode"
            height: 60
            toolbar: description_toolbar


    plugins:
        bbcode:
            path:     "ckeditor/plugins/bbcode/" # with trailing slash
            filename: "plugin.js"
        specialchar:
            path:     "ckeditor/plugins/specialchar"
            filename:  "plugin.js"


    toolbars:
        configs:
            description_toolbar: [ ["Source", "-", 'Bold', 'Italic', "-", "RemoveFormat", "-", "Smiley", "SpecialChar"] ]
