twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig', 'Form/extendedBootstrap4_layout.html.twig', 'Form/permissionLayout.html.twig' ]

    paths:
        '%kernel.project_dir%/assets/css': css

    globals:
        partdb_title: '%partdb_title%'
        default_currency: '%default_currency%'
        global_theme: '%global_theme%'
        allow_email_pw_reset: '%allow_email_pw_reset%'
        locale_menu: '%locale_menu%'
        attachment_manager: '@App\Services\Attachments\AttachmentManager'
        label_profile_dropdown_helper: '@App\Services\LabelSystem\LabelProfileDropdownHelper'
