twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig', 'Form/extendedBootstrap4_layout.html.twig', 'Form/permissionLayout.html.twig' ]
    exception_controller: ~

    globals:
        partdb_title: '%partdb_title%'
        default_currency: '%default_currency%'
        global_theme: '%global_theme%'
