language: php

env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled # Disable deprecation warnings

# Test for all supported PHP versions
php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer install

script:
  - php bin/phpunit