language: php

services:
  - mysql

env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled APP_ENV=test # Disable deprecation warnings

# Test for all supported PHP versions
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - 'nightly'

install:
  - composer install
  - php bin/console --env test doctrine:database:create --if-not-exists -n
# Migration is just for testing if it work, it is overwritten immediately
  - php bin/console --env test doctrine:migrations:migrate -n
# Load fixtures (workaround https://github.com/doctrine/DoctrineFixturesBundle/issues/50)
  - php bin/console --env test doctrine:schema:drop --force
  - php bin/console --env test doctrine:schema:update --force
  - php bin/console --env test doctrine:fixtures:load -n

script:
  - php bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly