language: php

services:
  - mysql

env:
  - SYMFONY_DEPRECATIONS_HELPER=disabled # Disable deprecation warnings
  - APP_ENV=test

# Test for all supported PHP versions
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - 'nightly'

before_install:
  - mysql -e 'CREATE DATABASE part-db_test;'

install:
  - composer install
  - php bin/console --env test doctrine:migrations:migrate -n
  - php bin/console --env test doctrine:fixtures:load -n

script:
  - php bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly