controllers:
    resource: ../../src/Controller/
    type: annotation

    prefix: '{_locale}'
    requirements:
        # Match only locales like de_DE or de
        _locale: "^[a-z]{2}(_[A-Z]{2})?$"
