2fa_login:
    path: /{_locale}/2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /{_locale}/2fa_check

r_u2f_register:
    resource: "@RU2FTwoFactorBundle/Resources/config/routing.yml"
    prefix: /{_locale}/user