#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Redirect every url without an locale to the locale of the user/the global base locale
redirector:
    path: /{url}
    requirements:
        url: ".*"
    controller: App\Controller\RedirectController:addLocalePart