#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Redirect every url without an locale to the locale of the user/the global base locale
redirector:
    path: /{url}
    requirements:
        url: ".*"
    controller: App\Controller\RedirectController:addLocalePart
    # Dont match localized routes (no redirection loop, if no root with that name exists)
    condition: "not (request.getPathInfo() matches '/^\\\\/[a-z]{2}(_[A-Z]{2})?\\\\//')"