title: Part-DB
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: "https://part-db.github.io"
baseurl: "/Part-DB-symfony" # the subpath of your site, e.g. /blog

aux_links:
  Part-DB Repository: https://github.com/Part-DB/Part-DB-symfony


search_enabled: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Part-DB/Part-DB-symfony" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately